import { PERMISSIONS, ROLES } from '../constants'

export const rolePermissions = {
	[ROLES.ADMIN]: [
		PERMISSIONS.CREATE_CONTENTS,
		PERMISSIONS.UPDATE_CONTENTS,
		PERMISSIONS.DELETE_CONTENTS,
        PERMISSIONS.VIEW_ADMIN_PAGE,
	],
	[ROLES.USER]: [PERMISSIONS.READ_PROFILE, PERMISSIONS.UPDATE_PROFILE],
};